Repository Chatting-App-FE/Chatting-App-FE, pull requests merged in 2023-11, with the labels that each got.

#5 Design: 전체 레이아웃 구성 및 폰트 , 테마 설정
  .prettierrc.json
  package-lock.json
  src/components/SideBar/SideBar.tsx
  src/index.css
  src/index.tsx
  src/layout.tsx
Labels: design

#7 Design: 채팅 레이아웃 구현
  src/App.tsx
  src/components/chats/ChatInput.tsx
  src/components/chats/ChatList.tsx
  src/components/chats/index.tsx
  src/pages/chats/index.tsx
Labels: design

#10 Feat: 채팅 카드 컴포넌트 제작
  .gitignore
  src/components/cardContainer/Card.tsx
  src/components/cardContainer/card.types.ts
  src/components/cardContainer/index.tsx
  src/constants/time.ts
  src/hooks/useChannels.ts
  src/index.tsx
  src/utils/channelName.ts
  src/utils/formatTimeToKST.ts
  src/utils/index.ts
Labels: feat

#11 Feat: ChatList api 연동
  package-lock.json
  package.json
  src/@types/message.ts
  src/@types/user.ts
  src/api/axios.ts
  src/api/socket.ts
  src/api/user.ts
  src/components/chats/ChatList.tsx
  src/components/chats/index.tsx
  src/constants/socket.ts
  src/constants/url.ts
Labels: feat

#16 refactor: 공통 타입,상수,instance 리팩토링
  src/@types/chat.ts
  src/@types/message.ts
  src/api/axios.ts
  src/api/socket.ts
  src/api/useGetUsers.ts
  src/api/user.ts
  src/components/cardContainer/Card.tsx
  src/constants/apiUrl.ts
  src/constants/appClient.ts
  src/constants/url.ts
  src/utils/index.ts
Labels: refactor

#17 Fix: channel 관련 import 오류 수정 및 이름 변경
  src/@types/chat.ts
  src/api/channel.ts
  src/components/ChannelList/Channel.tsx
  src/components/ChannelList/index.tsx
  src/constants/channel.ts
  src/hooks/useChannels.ts
Labels: fix

#18 Feat: 채팅 메시지 보내기 기능 구현
  src/@types/chat.ts
  src/@types/message.ts
  src/components/chats/ChatInput.tsx
  src/components/chats/ChatList.tsx
  src/components/chats/index.tsx
  src/constants/socket.ts
Labels: feat

#19 Feat: MyChannels api연동
  package-lock.json
  src/api/channel.ts
  src/components/SideBar/SideBar.tsx
  src/components/sideBar/MyChannelItem.tsx
  src/components/sideBar/index.tsx
  src/components/sideBar/modal/UserInviteList.tsx
  src/components/sideBar/modal/UserInviteModal.tsx
  src/hooks/useMyChannels.ts
  src/hooks/useUserData.ts
  src/index.tsx
  src/layout.tsx
Labels: feat

#21 Feat: 채널 생성 모달 제작
  src/@types/chat.ts
  src/api/channel.ts
  src/components/channel/ChannelCard.tsx
  src/components/channel/index.tsx
  src/components/channel/modal/CategoryInput.tsx
  src/components/channel/modal/CategoryRadio.tsx
  src/components/channel/modal/CreateChannelModal.tsx
  src/constants/channel.ts
  src/index.tsx
  src/recoil/channel.atom.ts
Labels: feat

#23 Feat: 실시간 채팅 메시지 보내기 구현
  src/@types/channel.ts
  src/@types/message.ts
  src/App.tsx
  src/api/channel.ts
  src/api/chat.ts
  src/api/socket.ts
  src/api/user.ts
  src/components/ChannelList/Channel.tsx
  src/components/chats/ChatList.tsx
  src/constants/socket.ts
  src/hooks/useChannels.ts
  src/hooks/useChatList.ts
  src/layout.tsx
Labels: feat

#25 Feat: 채팅방 생성 모달에 유저 선택 기능 추가
  src/App.tsx
  src/api/channel.ts
  src/api/user.ts
  src/components/channel/ChannelCard.tsx
  src/components/channel/index.tsx
  src/components/channel/modal/ChannelModalUserList.tsx
  src/components/channel/modal/CreateChannelModal.tsx
  src/constants/channel.ts
  src/constants/user.ts
  src/hooks/useUsers.ts
  src/pages/channel/index.tsx
  src/utils/channelName.ts
Labels: feat

#30 Feat : 채팅방 참여 멤버 리스트 구현
  src/@types/channel.ts
  src/api/channel.ts
  src/api/user.ts
  src/components/channel/modal/ChannelModalUserList.tsx
  src/components/channelMemberSideBar/ChannelMemberItem.tsx
  src/components/channelMemberSideBar/ChannelMemberList.tsx
  src/components/channelMemberSideBar/index.tsx
  src/components/channelMemberSideBar/modal/UserInviteList.tsx
  src/components/channelMemberSideBar/modal/UserInviteModal.tsx
  src/components/sideBar/index.tsx
  src/components/sideBar/modal/UserInviteList.tsx
  src/hooks/useMyChannels.ts
  src/pages/chats/index.tsx
Labels: feat

#33 Feat: useScroll 구현
  src/api/chat.ts
  src/api/socket.ts
  src/components/chats/ChatInput.tsx
  src/components/chats/ChatList.tsx
  src/components/chats/ChatListSkeleton.tsx
  src/components/chats/index.tsx
  src/hooks/useChatList.ts
  src/hooks/useScroll.ts
Labels: feat

#37 Feat: 채팅방 joiner leaver toast message 기능 구현
  src/api/chat.ts
  src/api/socket.ts
  src/components/chats/ChatList.tsx
  src/constants/chats.ts
  src/constants/socket.ts
  src/hooks/useChatList.ts
  src/layout.tsx
  src/pages/chats/index.tsx
  src/utils/chat.ts
Labels: feat

#29 Fix/Refactor: 유저 초대 컴포넌트 최적화 및 에러 해결
  src/api/channel.ts
  src/components/channel/modal/ChannelModalUser.tsx
  src/components/channel/modal/ChannelModalUserList.tsx
  src/components/channel/modal/CreateChannelModal.tsx
  src/hooks/useUsers.ts
  src/utils/channelName.ts
Labels: fix, refactor

#38 Feat: 채팅방 목록 검색 기능 추가
  package-lock.json
  package.json
  src/api/channel.ts
  src/components/ChannelList/Channel.tsx
  src/components/ChannelList/index.tsx
  src/components/channel/ChannelSearchInput.tsx
  src/components/channel/LoadingSkeleton.tsx
  src/components/channel/MyChannels.tsx
  src/components/channel/index.tsx
  src/components/channel/modal/CategoryRadio.tsx
  src/components/channel/modal/CreateChannelModal.tsx
  src/hooks/useChannels.ts
  src/hooks/useUsers.ts
  src/index.tsx
  src/pages/channel/index.tsx
  src/utils/channelName.ts
Labels: feat

#40 Feat: 멤버 사이드바 실시간 업데이트 & 온라인 유저 표현
  package-lock.json
  package.json
  src/@types/channel.ts
  src/@types/user.ts
  src/App.tsx
  src/api/channel.ts
  src/api/socket.ts
  src/components/channelMemberSideBar/ChannelMemberItem.tsx
  src/components/channelMemberSideBar/index.tsx
  src/components/channelMemberSideBar/modal/ChannelExitDialog.tsx
  src/components/channelMemberSideBar/modal/UserInviteList.tsx
  src/components/channelMemberSideBar/modal/UserInviteModal.tsx
  src/components/sideBar/MyChannelItem.tsx
  src/components/sideBar/index.tsx
  src/constants/socket.ts
  src/hooks/useJoinLeaveChannel.ts
  src/hooks/useMyChannels.ts
Labels: feat

#44 Fix: Merge 해결 및 추후 작업 예정 베이스
  package-lock.json
  package.json
  src/components/AllUserBar/index.tsx
  src/components/channel/ChannelRadio.tsx
  src/components/channel/ChannelSearchInput.tsx
  src/components/channel/ChannelSelector.tsx
  src/components/channel/index.tsx
  src/components/channel/modal/CategoryInput.tsx
  src/components/channel/modal/CategoryRadio.tsx
  src/components/channel/modal/CreateChannelModal.tsx
  src/constants/channel.ts
  src/pages/channel/index.tsx
  src/recoil/channel.atom.ts
  src/utils/channelName.ts
Labels: fix

#45 Feat: 회원가입 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/chats/index.tsx
  src/components/join/JoinIdInputBox.tsx
  src/components/join/JoinImageInputBox.tsx
  src/components/join/JoinInputBox.tsx
  src/constants/join.ts
  src/pages/join/index.tsx
Labels: feat

#49 나의 채널 보기 & 채팅방 클릭 시 모달 & 레이아웃 변경
  src/App.tsx
  src/components/AllUserBar/index.tsx
  src/components/channel/ChannelCard.tsx
  src/components/channel/MyChannels.tsx
  src/components/channel/index.tsx
  src/components/channel/modal/EnterChannelModal.tsx
  src/layout.tsx
  src/pages/channel/index.tsx
  src/utils/channelName.ts
Labels: feat

#48 feat: 회원가입 페이지 api 연동
  src/@types/join.ts
  src/api/join.ts
  src/components/join/JoinIdInputBox.tsx
  src/components/join/JoinImageInputBox.tsx
  src/hooks/join.ts
  src/pages/join/index.tsx
Labels: feat

#51 feat: chatId에 따른 페이지 렌더링 구현
  src/api/chat.ts
  src/api/socket.ts
  src/api/user.ts
  src/components/channelMemberSideBar/index.tsx
  src/components/chats/ChatInput.tsx
  src/components/chats/ChatList.tsx
  src/components/chats/index.tsx
  src/components/sideBar/MyChannelItem.tsx
  src/components/sideBar/index.tsx
  src/hooks/useChatList.ts
  src/hooks/useJoinLeaveChannel.ts
  src/hooks/useScroll.ts
  src/hooks/useUser.ts
  src/pages/chats/index.tsx
Labels: feat

#52 feat: 로그인 페이지 레이아웃 및 기능 개발
  src/@types/login.ts
  src/App.tsx
  src/api/login.ts
  src/components/login/loginInputBox.tsx
  src/constants/login.ts
  src/pages/login/index.tsx
Labels: feat, design

#50 Fix: 유저목록에서 온라인 유저 표시 기능 일시 삭제 및 수정
  src/@types/user.ts
  src/api/serverSocket.ts
  src/api/user.ts
  src/components/channel/modal/CategoryRadio.tsx
  src/components/channelMemberSideBar/ChannelMemberItem.tsx
  src/components/channelMemberSideBar/index.tsx
  src/components/channelMemberSideBar/modal/UserInviteList.tsx
  src/components/channelMemberSideBar/modal/UserInviteModal.tsx
  src/components/sideBar/index.tsx
  src/constants/channel.ts
  src/constants/socket.ts
  src/hooks/useChannels.ts
  src/hooks/useInviteData.ts
  src/hooks/useJoinLeaveChannel.ts
  src/hooks/useMyChannels.ts
Labels: fix

#54 feat: 로그인 시 토큰 인증 및 axios interceptor 설정
  src/App.tsx
  src/api/axios.ts
  src/api/refreshToken.ts
  src/api/socket.ts
  src/components/login/loginInputBox.tsx
  src/pages/login/index.tsx
Labels: feat

#56 Feat: 내 채팅목록 실시간 업데이트 구현
  src/api/serverSocket.ts
  src/components/sideBar/MyChannelItem.tsx
  src/components/sideBar/index.tsx
  src/constants/socket.ts
  src/hooks/useInviteData.ts
  src/hooks/useJoinLeaveChannel.ts
Labels: feat

#58 Fix: 전체 채널 목록 라우터 설정 수정
  src/App.tsx
Labels: fix

#59 fix: disconnect 및 type Error 수정
  src/api/axios.ts
  src/api/login.ts
  src/hooks/useChatList.ts
  src/hooks/useInviteData.ts
  src/hooks/useJoinLeaveChannel.ts
Labels: fix

#63 design: 디자인 디테일 수정 입니다!
  src/components/AllUserBar/index.tsx
  src/components/channel/ChannelCard.tsx
  src/components/channel/ChannelRadio.tsx
  src/components/sideBar/index.tsx
  src/constants/channel.ts
  src/pages/channel/index.tsx
Labels: design

#65 design: 사이드바, 채팅멤버 사이드바 세부 디자인
  src/components/channelMemberSideBar/index.tsx
  src/components/channelMemberSideBar/modal/ChannelExitDialog.tsx
  src/components/channelMemberSideBar/modal/UserInviteModal.tsx
  src/components/sideBar/MyChannelItem.tsx
  src/components/sideBar/index.tsx
  src/hooks/useInviteData.ts
Labels: design

#69 fix: 빌드 시 웹 소켓 통신 에러 해결
  src/api/socket.ts
  src/components/channelMemberSideBar/index.tsx
  src/components/channelMemberSideBar/modal/ChannelExitDialog.tsx
  src/components/channelMemberSideBar/modal/UserInviteModal.tsx
  src/components/sideBar/MyChannelItem.tsx
  src/components/sideBar/index.tsx
  src/hooks/useInviteData.ts
Labels: fix

#71 Feat: 참가하기 구현
  src/api/channel.ts
  src/components/channel/modal/EnterChannelModal.tsx
  src/components/sideBar/index.tsx
  src/hooks/useInviteData.ts
Labels: feat

#74 Design: favicon 추가
  public/favicon.ico
  public/index.html
  src/api/serverSocket.ts
Labels: design

#75 design: 사이드바 width값 조절
  src/components/channelMemberSideBar/index.tsx
Labels: design

#76 design: membersidebar width 조정
  src/components/channelMemberSideBar/index.tsx
  src/pages/login/index.tsx
Labels: fix, design
